---
id: uniswapCourse
name: Uniswap Course
summary: Learn how to create a Uniswap swap contract using Solidity. Developed by the p2p learning platform https://dacade.org.
tags:
  - Solidity
  - Tokens
  - Uniswap
steps:
  - name: 1. Introduction
    path: 1-introduction-to-uniswap

  - name: 2. Routers, Interfaces, and Structs
    path: 2-router-interfaces-and-structs

  - name: 3. Single Hop Swaps
    path: 3-single-hop-swaps

  - name: 4. Multi-Hop Swaps
    path: 4-multi-hop-swaps

  - name: 5. Erc20 and Weth Interfaces
    path: 5-erc20-weth-interfaces
